# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Hailey
tagline:          'hailey Ground'
description:      'For Full Stacker, always learning. <a href="https://github.com/jungAcat/" target="_blank">GitHub</a> '
url:              https://jungacat.github.io/
baseurl:          /

author:
  name:           'Hailey Na'
  url:            https://jungacat.github.io/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
